### PR TITLE
Fix semgrep dgryski.semgrep-go issues

### LINKED ISSUE #3509: fix semgrep issues with https://github.com/dgryski/semgrep-go ruleset
We need to fix these issues flagged by semgrep when run with the https://github.com/dgryski/semgrep-go ruleset ruleset:
https://gist.github.com/dmitris/908a85d205249f2018f4688308fb5053
```bash
semgrep --config http://semgrep.dev/r/dgryski.semgrep-go
┌──────────────────┐
│ 15 Code Findings │
└──────────────────┘
[...]
```

Related to https://github.com/prebid/prebid-server/issues/1551.

### PR DESCRIPTION
**Pull request by dmitris**
Fix most of the semgrep issues with the
http://semgrep.dev/r/dgryski.semgrep-go ruleset
(`semgrep --config http://semgrep.dev/r/dgryski.semgrep-go`). Left the issue with Content-Type text/plain on json.Encode in endpoints/openrtb2/amp_auction.go since changing to application/json breaks the AMP unit tests, and issues with the pointer receiver for MarshalJSON in usersync/cookie.go.

Fix #3509.

### CODE REVIEW

File: endpoints/openrtb2/amp_auction.go [hunk 1]
```diff
@@ -387,6 +387,7 @@ func sendAmpResponse(
 	// Fixes #231
 	enc := json.NewEncoder(w)
 	enc.SetEscapeHTML(false)
+	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
```
Comment (SyntaxNode) [inline endpoints/openrtb2/amp_auction.go:390]: Why is it necessary to add this header set?

Comment (dmitris) [reply endpoints/openrtb2/amp_auction.go:390]: it is done any way - added it explicitly to make clear that the text encoding is intended despite the JSON encoding (I assume due to the AMP requirements).  Would you prefer to remove it? @SyntaxNode

Comment (bsardo) [reply endpoints/openrtb2/amp_auction.go:390]: @SyntaxNode and I discussed offline. You're correct in that `text/plain` is what PBS-Go returns. We're not sure why that is as it predates us and I can't find any documentation on the subject. I did notice that `application/json` is returned by PBS-Java in the 200 success case, which is probably what the content type should be. However, I suggest we keep the behavior as `text/plain` since it has been this way for years without complaint and keep this line of code but add a comment above it that is something like:
"Explicitly set content type to text/plain, which had previously been the implied behavior from the time the project was launched. It's unclear why text/plain was chosen or if it was an oversight, nevertheless we will keep it as such for compatibility reasons"

**Comment by SyntaxNode** [comment]
@dmitris We discussed the content-type change. Please review the comment from @bsardo. We're recommending a comment to provide additional context and are good with the change.

**Comment by dmitris** [comment]
> @dmitris We discussed the content-type change. Please review the comment from @bsardo. We're recommending a comment to provide additional context and are good with the change.

done in a3c9e362, thanks

**Review by guscarreon — COMMENTED** [review]
Changes in `usersync/encoder.go` and `config/usersync.go` do not seem to be listed in the [prebid-semgrep-dgryski.txt](https://gist.github.com/dmitris/908a85d205249f2018f4688308fb5053). What's the reason behind the `EncoderSigner` interface? Why do we need `HMACSignature` config field?

**Review by guscarreon — COMMENTED** [review]
> I'm sorry 

Don't be sorry @dmitris. Thank you for fixing this. Left a minor nitpick below

File: endpoints/openrtb2/amp_auction.go [hunk 2]
```diff
@@ -398,8 +398,13 @@ func sendAmpResponse(
 	ao.AmpTargetingValues = targets
 
 	// Fixes #231
-	enc := json.NewEncoder(w)
+	enc := json.NewEncoder(w) // nosemgrep: json-encoder-needs-type
```
[the remark this answers is not in the document]
Comment (dmitris) [reply endpoints/openrtb2/amp_auction.go:401]: without the `nosemgrep` ignore, semgrep run produces the following finding:
```sh
    endpoints/openrtb2/amp_auction.go
   ❯❯❱ Users.dmitris.gh.dgryski.semgrep-go.json-encoder-needs-type
          calling json.Encode() on an http.ResponseWriter will set Content-
          Type text/plain

          401┆ enc := json.NewEncoder(w)
          402┆ enc.SetEscapeHTML(false)
          403┆ // Explicitly set content type to text/plain, which had
               previously been
          404┆ // the implied behavior from the time the project was
               launched.
          405┆ // It's unclear why text/plain was chosen or if it was an
               oversight,
          406┆ // nevertheless we will keep it as such for compatibility
               reasons.
          407┆ w.Header().Set("Content-Type", "text/plain;
               charset=utf-8")
          408┆
```

actually there is another similar one in `usersync/cookie.go`:
```sh
    usersync/cookie.go
   ❯❯❱ Users.dmitris.gh.dgryski.semgrep-go.marshal-json-pointer-receiver
          MarshalJSON with a pointer receiver has surprising results:
          https://github.com/golang/go/issues/22967

          228┆ func (cookie *Cookie) MarshalJSON() ([]byte, error) {
```

Do we want or can we change the pointer receiver to by-value `Cookie`? This is part of the public (exported) interface of the package.  I think for this PR we should either add the `// nosemgrep` skip to both cases, or remove the `nosemgrep` and leave it with the flagged findings.  I've done the former for now - 9cc55f48 adding another `nosemgrep` to get a clean semgrep run (and for the new issues to "stick out" if they appear), but if you prefer, I can remove both `// nosemgrep` comments.

[the remark this answers is not in the document]
Comment (guscarreon) [reply endpoints/openrtb2/amp_auction.go:401]: Interesting. I'm ok with leaving the `nosemgrep` comments for now.

**Review by guscarreon — APPROVED** [review]
LGTM. Thanks for addressing my feedback

**Review by AlexBVolcy — APPROVED** [review]
