### PR TITLE
Prevent Fetcher calls on duplicate Stored Request IDs

### LINKED ISSUE #311: Stored Request Fetchers called unnecessarily on repeated IDs
To reproduce: Configure PBS to use an `in_memory_cache` for Stored Requests.

Make two identical Requests with two different `Imp` values which both use the same Stored Request IDs.

Expected behavior: The `Fetcher` should not be called on the second Request, because the `Cache` already has the required data in it.

Observed behavior: The `Fetcher` gets called with `[]string{""}`

### PR DESCRIPTION
**Pull request by dbemiller**
Fixes #311.

### CODE REVIEW

File: stored_requests/fetcher.go [hunk 1]
```diff
@@ -52,16 +52,23 @@ type fetcherWithCache struct {
 
 func (f *fetcherWithCache) FetchRequests(ctx context.Context, ids []string) (data map[string]json.RawMessage, errs []error) {
 	data = f.cache.GetRequests(ctx, ids)
-	if len(data) >= len(ids) {
+
```
Comment (hhhjort) [inline stored_requests/fetcher.go]: Wouldn't it be easier to check leftoverIds below, and then if == 0 "return data, nil", rather than doing this extra loop? That still gets us out before trying to look up an empty list.

Comment (dbemiller) [reply stored_requests/fetcher.go]: Actually on looking into it... we don't even need that. The issue is fixed just by changing the way I generate the IDs we send to the `Fetcher`.

It also surfaced another extra check I could delete. Since we don't know whether the PBS host is running with a cache, the `Fetcher` needs to be smart enough to return quickly on empty lists in the first place. Given that, it means there's also no real value in doing check to see if we have an empty list before making the function call.

Stuff is much simplified now.

File: stored_requests/fetcher.go [hunk 2]
```diff
@@ -52,16 +52,12 @@ type fetcherWithCache struct {
...
 func (f *fetcherWithCache) FetchRequests(ctx context.Context, ids []string) (data map[string]json.RawMessage, errs []error) {
 	data = f.cache.GetRequests(ctx, ids)
-	if len(data) >= len(ids) {
-		return data, nil
-	}
 
-	leftoverIds := make([]string, len(ids)-len(data))
-	currentIndex := 0
+	// Fixes #311
+	leftoverIds := make([]string, 0, len(ids)-len(data))
```
Comment (anwzhang) [inline stored_requests/fetcher.go]: What is this leftoverIds used for? what are ids and what is data?

Comment (dbemiller) [reply stored_requests/fetcher.go]: `ids` are the IDs of the Stored Request which someone wants to fetch.
`data` is a map from ID to Stored Request. This contains everything the cache returns

`leftoverIds` is the subset of `ids` which _aren't_ included in `data`. After that loop, it should only have the elements of `ids` which were _not_ found in the Cache.

Comment (anwzhang) [reply stored_requests/fetcher.go]: I don't see differences from this diff. Both are sending the same set of leftoverids to Fetcher later, right?

Comment (dbemiller) [reply stored_requests/fetcher.go]: They're not. If `ids` has duplicate values, then the `map` will have one fewer, because maps automatically filter out duplicates... so the lengths were wrong.

If you run the regression test I added against the `master` code, you can see it fail.
