### PR TITLE
Defines defaults for all config options and removes pointers from the…

### LINKED ISSUE #475: App config values aren't used as expected
To reproduce:

1. Define a `pbs.yaml` file which _doesn't_ include an entry for `status_response: "stuff"`
2. Build PBS and set the environment variable with `export PBS_STATUS_RESPONSE=something`
3. Run `GET localhost:8000/status`

Expected:

- The `/status` endpoint should return "something".

Observed:

- A 204 is returned because the config value was empty.

------------------------------------------------------------

Even more unusual: define a `pbs.yaml` which _does_ include an entry for `status_response: "something-else"`

Restart the PBS app. Now the `PBS_STATUS_RESPONSE` environment variable will be in effect.

### PR DESCRIPTION
**Pull request by hhhjort**
… Configuration struct

This will allow Viper to read environment variables into the config for all config options. Fixes #475 

Copying this to the top so people can easily find the breaking change:
Before this, A config like:

stored_requests:
  postgres:
    in_memory_cache:
      ttl_seconds: ###
      request_cache_size_bytes: ###
      imp_cache_size_bytes: ###
would create an in-memory stored request cache.

After this, it needs a Type should be:

stored_requests:
  postgres:
    in_memory_cache:
      type: "unbounded"   // could also be "none" or "lru"
      ttl_seconds: ###
      request_cache_size_bytes: ###
      imp_cache_size_bytes: ###
The ttl_seconds, request_cache_size_bytes, and imp_cache_size_bytes will only apply to lru caches.

That makes this a breaking change for PBS hosts.

### CODE REVIEW

File: stored_requests/config/config.go [hunk 1]
```diff
@@ -84,12 +84,12 @@ func newFetchers(cfg *config.StoredRequests, client *http.Client, db *sql.DB) (f
 		idList = append(idList, fFetcher)
 		ampIDList = append(ampIDList, fFetcher)
 	}
-	if cfg.Postgres != nil {
+	if cfg.Postgres.FetcherQueries.QueryTemplate != "" {
```
Comment (dbemiller) [inline stored_requests/config/config.go]: Do you think we should split this into two clauses now? Someone might define `QueryTemplate` and not `AmpQueryTemplate`, or vice versa.

Otherwise we should add some `validate()` logic to make sure that both or neither are defined... but I lean towards changing the logic here so that it works either way.

File: stored_requests/config/config.go [hunk 2]
```diff
@@ -84,12 +84,12 @@ func newFetchers(cfg *config.StoredRequests, client *http.Client, db *sql.DB) (f
...
 		glog.Infof("Loading Stored Requests via Postgres.\nQuery: %s\nAMP Query: %s", cfg.Postgres.FetcherQueries.QueryTemplate, cfg.Postgres.FetcherQueries.AmpQueryTemplate)
 		idList = append(idList, db_fetcher.NewFetcher(db, cfg.Postgres.FetcherQueries.MakeQuery))
 		ampIDList = append(ampIDList, db_fetcher.NewFetcher(db, cfg.Postgres.FetcherQueries.MakeAmpQuery))
 	}
-	if cfg.HTTP != nil {
+	if cfg.HTTP.Endpoint != "" {
```
Comment (dbemiller) [inline stored_requests/config/config.go]: Same issue goes here, with `Endpoint` and `AmpEndpoint`

File: stored_requests/config/config.go [hunk 3]
```diff
@@ -101,45 +101,44 @@ func newFetchers(cfg *config.StoredRequests, client *http.Client, db *sql.DB) (f
 }
 
 func newCache(cfg *config.StoredRequests) stored_requests.Cache {
-	if cfg.InMemoryCache == nil {
+	if cfg.InMemoryCache.RequestCacheSize == 0 {
```
Comment (dbemiller) [inline stored_requests/config/config.go]: eh... this will actually cause problems. See the docs on `InMemoryCache`:

```
// RequestCacheSize is the max number of bytes allowed in the cache for Stored Requests. Values <= 0 will have no limit
```

File: stored_requests/config/config.go [hunk 4]
```diff
@@ -101,45 +101,44 @@ func newFetchers(cfg *config.StoredRequests, client *http.Client, db *sql.DB) (f
...
 		eventProducers = append(eventProducers, newEventsAPI(router, "/storedrequests/openrtb2"))
 		ampEventProducers = append(ampEventProducers, newEventsAPI(router, "/storedrequests/amp"))
 	}
-	if cfg.HTTPEvents != nil {
+	if cfg.HTTPEvents.RefreshRate != 0 {
 		eventProducers = append(eventProducers, newHttpEvents(client, cfg.HTTPEvents.TimeoutDuration(), cfg.HTTPEvents.RefreshRateDuration(), cfg.HTTPEvents.Endpoint))
 		ampEventProducers = append(ampEventProducers, newHttpEvents(client, cfg.HTTPEvents.TimeoutDuration(), cfg.HTTPEvents.RefreshRateDuration(), cfg.HTTPEvents.AmpEndpoint))
 	}
-	if cfg.Postgres != nil {
+	if cfg.Postgres.CacheInitialization.Query != "" {
```
Comment (dbemiller) [inline stored_requests/config/config.go]: Same issue with `Query` and `AmpQuery` here

**Comment by dbemiller** [comment]
Fixes #475

File: pbs_light.go [hunk 5]
```diff
@@ -618,16 +618,58 @@ func init() {
 	viper.AddConfigPath(".")
 	viper.AddConfigPath("/etc/config")
 
+	// Some defaults will be set just so they are accessable via environment variables
+	// (basically so viper knows they exist)
```
Comment (dbemiller) [inline pbs_light.go]: Could you start this comment with `// Fixes #475: {description}`?

It's searchable by grep/find/whatever, and points confused engineers to the discussion which caused the code.

File: stored_requests/config/config.go (hunk 1 above)
Comment (hhhjort) [reply stored_requests/config/config.go]: I think our logic breaks in other places if someone defines one and not the other. Before if the struct was not null, we just assumed we had both and configured the fetchers appropriately. We will likely have to dive deeper into our code if we want to support piecemeal configs.

File: stored_requests/config/config.go (hunk 3 above)
Comment (hhhjort) [reply stored_requests/config/config.go]: I will have to add a `use_memory_cache` property, as it is a valid config to have all other cache properties be their zero values (just not all zero at the same time as that would be unlimited cache size with no expirery)

File: stored_requests/config/config.go (hunk 1 above)
Comment (dbemiller) [reply stored_requests/config/config.go]: if it doesn't work today, separate PR.

File: stored_requests/config/config.go (hunk 3 above)
Comment (dbemiller) [reply stored_requests/config/config.go]: yeah, that sounds right.

Alternatively you could add a `cfg.InMemoryCache.Type` with values `none`, `unbounded` and `lru`, and then `cfg.InMemoryCache.LRU` with the LRU-specific configs.

I just mention it because that pattern was used consistently in `prebid-cache`, and it worked out pretty well... but either one would work for now.

File: stored_requests/config/config.go (hunk 1 above)
Comment (hhhjort) [reply stored_requests/config/config.go]: Fixing the base issues was enough work for this PR. Adding support for partial configs (something we don't support today) left for another PR.

File: config/config.go [hunk 6]
```diff
@@ -198,3 +198,96 @@ func (cfg *Cache) GetBaseURL() string {
 func (cfg *Configuration) GetCachedAssetURL(uuid string) string {
 	return fmt.Sprintf("%s/cache?%s", cfg.CacheURL.GetBaseURL(), strings.Replace(cfg.CacheURL.Query, "%PBS_CACHE_UUID%", uuid, 1))
 }
+
+// Set the default config values for the viper object we are using.
+func ConfigViper(v *viper.Viper) {
```
Comment (dbemiller) [inline config/config.go]: opinion: `SetDefaults` might be a bit more clear?

File: config/config_test.go [hunk 7]
```diff
@@ -9,7 +9,12 @@ import (
 )
 
 func TestDefaults(t *testing.T) {
-	cfg, err := New(newViperWithDefaults())
+	v := viper.New()
+	ConfigViper(v)
+	v.SetDefault("auction_timeouts_ms.max", 250)
```
Comment (dbemiller) [inline config/config_test.go]: This seems a bit weird...

This test targets the `ConfigViper` method, but this sets extra defaults and then asserts on them. Seems like these should go away, and the assertions replaced with the intended default values.

File: config/stored_requests.go [hunk 8]
```diff
@@ -316,6 +314,8 @@ func makeIdList(numSoFar int, numArgs int) string {
 }
 
 type InMemoryCache struct {
+	// Identify the type of memory cache. "none", "unbounded", "lru"
+	Type string `mapstructure:"type"`
```
Comment (dbemiller) [inline config/stored_requests.go]: I think this should be an enum? To identify the 3 legal values.

File: config/config.go (hunk 6 above)
Comment (dbemiller) [reply config/config.go]: `SetupViper` also sounds good.

I'm just shooting for something which publicizes the fact that it actually _mutates_ the argument object. `Set`, `Setup`, `Init`, etc. do that. `Configure` isn't bad either... but `Config` is used as a noun too frequently.

File: config/config_test.go (hunk 7 above)
Comment (hhhjort) [reply config/config_test.go]: The intended default values for these are the zero values, or a URL that has apparently changed in the past. I thought it was a weak test to test that zero values were still zero values, and I wasn't sure about changing the actual default values in this PR. Could just check for the current URL, and the test failure will prompt us to update the test if the URL changes again.

File: config/stored_requests.go (hunk 8 above)
Comment (hhhjort) [reply config/stored_requests.go]: Yes, would be more proper with an enum. :)

File: config/config_test.go (hunk 7 above)
Comment (dbemiller) [reply config/config_test.go]: ahh, gotcha. I agree, that makes sense.

In that case let's just remove those assertions. There's no value in testing test code.

File: config/stored_requests.go (hunk 8 above)
Comment (hhhjort) [reply config/stored_requests.go]: Actually, on second thought I think an enum would add overhead without any benefit. The config value only gets set from Viper, so any incoming string will be forced into the `MemCacheType` type, eliminating any constraints on the value that go "enum" could enforce. The code never changes this later, which is where type safety comes in. And finally, we have the `validate()` method we call after reading in the configuration that will enforce the value to be one of the list.

File: config/config_test.go (hunk 7 above)
Comment (hhhjort) [reply config/config_test.go]: Already replace, found a couple of ints with non-zero defaults to test for instead.

**Comment by dbemiller** [comment]
Before this, A config like:

```
stored_requests:
  postgres:
    in_memory_cache:
      ttl_seconds: ###
      request_cache_size_bytes: ###
      imp_cache_size_bytes: ###
```

would create an in-memory stored request cache.

After this, it needs a `Type` should be:

```
stored_requests:
  postgres:
    in_memory_cache:
      type: "unbounded"   // could also be "none" or "lru"
      ttl_seconds: ###
      request_cache_size_bytes: ###
      imp_cache_size_bytes: ###
```

The `ttl_seconds`, `request_cache_size_bytes`, and `imp_cache_size_bytes` will only apply to `lru` caches.

That makes this a breaking change for PBS hosts.

**Comment by hhhjort** [comment]
Oh, yes, that is true, thanks. I was hoping to do all this without introducing a breaking change, but then found that there were cases where a non-"none" cache could have a `0` in any one of the current parameters, so I needed to introduce the type. Didn't reconsider the label after I changed it.
